export interface ElementJapaneseName {
    atomicNumber: number;
    symbol: string;
    name: string;
    alias?: string;
}

export const elementJapaneseNameList: ElementJapaneseName[] = [
    { atomicNumber: 1, symbol: 'H', alias: "すいそ", name: "水素" },
    { atomicNumber: 2, symbol: 'He', name: "ヘリウム" },
    { atomicNumber: 3, symbol: 'Li', name: "リチウム" },
    { atomicNumber: 4, symbol: 'Be', name: "ベリリウム" },
    { atomicNumber: 5, symbol: 'B', name: "ホウ素" },
    { atomicNumber: 6, symbol: 'C', alias: "たんそ", name: "炭素" },
    { atomicNumber: 7, symbol: 'N', alias: "ちっそ", name: "窒素" },
    { atomicNumber: 8, symbol: 'O', alias: "さんそ", name: "酸素" },
    { atomicNumber: 9, symbol: 'F', name: "フッ素" },
    { atomicNumber: 10, symbol: 'Ne', name: "ネオン" },
    { atomicNumber: 11, symbol: 'Na', name: "ナトリウム" },
    { atomicNumber: 12, symbol: 'Mg', name: "マグネシウム" },
    { atomicNumber: 13, symbol: 'Al', name: "アルミニウム" },
    { atomicNumber: 14, symbol: 'Si', name: "ケイ素" },
    { atomicNumber: 15, symbol: 'P', name: "リン" },
    { atomicNumber: 16, symbol: 'S', alias: "いおう", name: "硫黄" },
    { atomicNumber: 17, symbol: 'Cl', alias: "えんそ", name: "塩素" },
    { atomicNumber: 18, symbol: 'Ar', name: "アルゴン" },
    { atomicNumber: 19, symbol: 'K', name: "カリウム" },
    { atomicNumber: 20, symbol: 'Ca', name: "カルシウム" },
    { atomicNumber: 21, symbol: 'Sc', name: "スカンジウム" },
    { atomicNumber: 22, symbol: 'Ti', name: "チタン" },
    { atomicNumber: 23, symbol: 'V', name: "バナジウム" },
    { atomicNumber: 24, symbol: 'Cr', name: "クロム" },
    { atomicNumber: 25, symbol: 'Mn', name: "マンガン" },
    { atomicNumber: 26, symbol: 'Fe', alias: "てつ", name: "鉄" },
    { atomicNumber: 27, symbol: 'Co', name: "コバルト" },
    { atomicNumber: 28, symbol: 'Ni', name: "ニッケル" },
    { atomicNumber: 29, symbol: 'Cu', alias: "どう", name: "銅" },
    { atomicNumber: 30, symbol: 'Zn', alias: "あえん", name: "亜鉛" },
    { atomicNumber: 31, symbol: 'Ga', name: "ガリウム" },
    { atomicNumber: 32, symbol: 'Ge', name: "ゲルマニウム" },
    { atomicNumber: 33, symbol: 'As', name: "ヒ素" },
    { atomicNumber: 34, symbol: 'Se', name: "セレン" },
    { atomicNumber: 35, symbol: 'Br', alias: "しゅうそ", name: "臭素" },
    { atomicNumber: 36, symbol: 'Kr', name: "クリプトン" },
    { atomicNumber: 37, symbol: 'Rb', name: "ルビジウム" },
    { atomicNumber: 38, symbol: 'Sr', name: "ストロンチウム" },
    { atomicNumber: 39, symbol: 'Y', name: "イットリウム" },
    { atomicNumber: 40, symbol: 'Zr', name: "ジルコニウム" },
    { atomicNumber: 41, symbol: 'Nb', name: "ニオブ" },
    { atomicNumber: 42, symbol: 'Mo', name: "モリブデン" },
    { atomicNumber: 43, symbol: 'Tc', name: "テクネチウム" },
    { atomicNumber: 44, symbol: 'Ru', name: "ルテニウム" },
    { atomicNumber: 45, symbol: 'Rh', name: "ロジウム" },
    { atomicNumber: 46, symbol: 'Pd', name: "パラジウム" },
    { atomicNumber: 47, symbol: 'Ag', name: "銀" },
    { atomicNumber: 48, symbol: 'Cd', name: "カドミウム" },
    { atomicNumber: 49, symbol: 'In', name: "インジウム" },
    { atomicNumber: 50, symbol: 'Sn', name: "スズ" },
    { atomicNumber: 51, symbol: 'Sb', name: "アンチモン" },
    { atomicNumber: 52, symbol: 'Te', name: "テルル" },
    { atomicNumber: 53, symbol: 'I', name: "ヨウ素" },
    { atomicNumber: 54, symbol: 'Xe', name: "キセノン" },
    { atomicNumber: 55, symbol: 'Cs', name: "セシウム" },
    { atomicNumber: 56, symbol: 'Ba', name: "バリウム" },
    { atomicNumber: 57, symbol: 'La', name: "ランタン" },
    { atomicNumber: 58, symbol: 'Ce', name: "セリウム" },
    { atomicNumber: 59, symbol: 'Pr', name: "プラセオジム" },
    { atomicNumber: 60, symbol: 'Nd', name: "ネオジム" },
    { atomicNumber: 61, symbol: 'Pm', name: "プロメチウム" },
    { atomicNumber: 62, symbol: 'Sm', name: "サマリウム" },
    { atomicNumber: 63, symbol: 'Eu', name: "ユウロピウム" },
    { atomicNumber: 64, symbol: 'Gd', name: "ガドリニウム" },
    { atomicNumber: 65, symbol: 'Tb', name: "テルビウム" },
    { atomicNumber: 66, symbol: 'Dy', name: "ジスプロシウム" },
    { atomicNumber: 67, symbol: 'Ho', name: "ホルミウム" },
    { atomicNumber: 68, symbol: 'Er', name: "エルビウム" },
    { atomicNumber: 69, symbol: 'Tm', name: "ツリウム" },
    { atomicNumber: 70, symbol: 'Yb', name: "イッテルビウム" },
    { atomicNumber: 71, symbol: 'Lu', name: "ルテチウム" },
    { atomicNumber: 72, symbol: 'Hf', name: "ハフニウム" },
    { atomicNumber: 73, symbol: 'Ta', name: "タンタル" },
    { atomicNumber: 74, symbol: 'W', name: "タングステン" },
    { atomicNumber: 75, symbol: 'Re', name: "レニウム" },
    { atomicNumber: 76, symbol: 'Os', name: "オスミウム" },
    { atomicNumber: 77, symbol: 'Ir', name: "イリジウム" },
    { atomicNumber: 78, symbol: 'Pt', alias: "はっきん", name: "白金" },
    { atomicNumber: 79, symbol: 'Au', alias: "きん", name: "金" },
    { atomicNumber: 80, symbol: 'Hg', alias: "すいぎん", name: "水銀" },
    { atomicNumber: 81, symbol: 'Tl', name: "タリウム" },
    { atomicNumber: 82, symbol: 'Pb', alias: "なまり", name: "鉛" },
    { atomicNumber: 83, symbol: 'Bi', name: "ビスマス" },
    { atomicNumber: 84, symbol: 'Po', name: "ポロニウム" },
    { atomicNumber: 85, symbol: 'At', name: "アスタチン" },
    { atomicNumber: 86, symbol: 'Rn', name: "ラドン" },
    { atomicNumber: 87, symbol: 'Fr', name: "フランシウム" },
    { atomicNumber: 88, symbol: 'Ra', name: "ラジウム" },
    { atomicNumber: 89, symbol: 'Ac', name: "アクチニウム" },
    { atomicNumber: 90, symbol: 'Th', name: "トリウム" },
    { atomicNumber: 91, symbol: 'Pa', name: "プロトアクチニウム" },
    { atomicNumber: 92, symbol: 'U', name: "ウラン" },
    { atomicNumber: 93, symbol: 'Np', name: "ネプツニウム" },
    { atomicNumber: 94, symbol: 'Pu', name: "プルトニウム" },
    { atomicNumber: 95, symbol: 'Am', name: "アメリシウム" },
    { atomicNumber: 96, symbol: 'Cm', name: "キュリウム" },
    { atomicNumber: 97, symbol: 'Bk', name: "バークリウム" },
    { atomicNumber: 98, symbol: 'Cf', name: "カリホルニウム" },
    { atomicNumber: 99, symbol: 'Es', name: "アインスタイニウム" },
    { atomicNumber: 100, symbol: 'Fm', name: "フェルミウム" },
    { atomicNumber: 101, symbol: 'Md', name: "メンデレビウム" },
    { atomicNumber: 102, symbol: 'No', name: "ノーベリウム" },
    { atomicNumber: 103, symbol: 'Lr', name: "ローレンシウム" },
    { atomicNumber: 104, symbol: 'Rf', name: "ラザホージウム" },
    { atomicNumber: 105, symbol: 'Db', name: "ドブニウム" },
    { atomicNumber: 106, symbol: 'Sg', name: "シーボーギウム" },
    { atomicNumber: 107, symbol: 'Bh', name: "ボーリウム" },
    { atomicNumber: 108, symbol: 'Hs', name: "ハッシウム" },
    { atomicNumber: 109, symbol: 'Mt', name: "マイトネリウム" },
    { atomicNumber: 110, symbol: 'Ds', name: "ダームスタチウム" },
    { atomicNumber: 111, symbol: 'Rg', name: "レントゲニウム" },
    { atomicNumber: 112, symbol: 'Cn', name: "コペルニシウム" },
    { atomicNumber: 113, symbol: 'Nh', name: "ニホニウム" },
    { atomicNumber: 114, symbol: 'Fl', name: "フレロビウム" },
    { atomicNumber: 115, symbol: 'Mc', name: "モスコビウム" },
    { atomicNumber: 116, symbol: 'Lv', name: "リバモリウム" },
    { atomicNumber: 117, symbol: 'Ts', name: "テネシン" },
    { atomicNumber: 118, symbol: 'Og', name: "オガネソン" },
]